{{- if .Values.httproute.enabled -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "slack-server-mcp.fullname" . }}
  labels:
    {{- include "slack-server-mcp.labels" . | nindent 4 }}
spec:
  parentRefs:
    - name: {{ .Values.httproute.gatewayName }}
      namespace: {{ .Values.httproute.gatewayNamespace | default .Release.Namespace }}
  hostnames:
    {{- range .Values.httproute.hostnames }}
    - {{ . | quote }}
    {{- end }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: {{ .Values.httproute.path | default "/" }}
      backendRefs:
        - name: {{ include "slack-server-mcp.fullname" . }}
          port: {{ .Values.mcp.server.port }}
{{- end }}