apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "google-search-mcp-server.fullname" . }}-config
  labels:
    {{- include "google-search-mcp-server.labels" . | nindent 4 }}
data:
  google-cse-id: {{ .Values.googleApi.cseId | quote }}
  {{- range $key, $value := .Values.configData }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}