apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "google-search-mcp.fullname" . }}
  labels:
    {{- include "google-search-mcp.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "google-search-mcp.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "google-search-mcp.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "google-search-mcp.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if eq .Values.mcp.transport "stdio" }}
          command: ["/bin/sh", "-c"]
          args: 
            - |
              echo "{{ include "google-search-mcp.serverDescription" . }} is ready (stdio mode)"
              echo "This server uses MCP (Model Context Protocol) via stdio"
              {{- if eq .Values.mcp.serverType "enhanced" }}
              echo "To connect, use: kubectl exec -it <pod-name> -- python enhanced_google_search_server.py"
              echo "Available tools: search_google, search_images, search_by_date_range, search_site_specific,"
              echo "                search_file_type, search_related, search_cached, get_search_suggestions, get_api_status"
              {{- else }}
              echo "To connect, use: kubectl exec -it <pod-name> -- python google_search_mcp_server.py"
              echo "Available tools: search_google"
              {{- end }}
              echo "Google API Key is configured and ready"
              
              # Keep container running for exec access
              while true; do
                sleep 300
                echo "MCP Server container is running - $(date)"
              done
          {{- else }}
          command: ["python", "{{ include "google-search-mcp.serverScript" . }}"]
          args:
            - "--transport"
            - "{{ .Values.mcp.transport }}"
            {{- if ne .Values.mcp.transport "stdio" }}
            - "--host"
            - "{{ .Values.mcp.server.host }}"
            - "--port"
            - "{{ .Values.mcp.server.port }}"
            {{- end }}
          {{- end }}
          env:
            - name: PYTHONPATH
              value: "/app"
            {{- if .Values.secret.externalConfigMap }}
            # Use external ConfigMap for environment variables
            - name: GOOGLE_API_KEY
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.secret.externalConfigMap }}
                  key: GOOGLE_API_KEY
            - name: GOOGLE_CSE_ID
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.secret.externalConfigMap }}
                  key: GOOGLE_CSE_ID
            {{- else if .Values.secret.useEnvVars }}
            # Use environment variables - either directly or via auto-created ConfigMap
            {{- if and .Values.secret.googleApiKey .Values.secret.googleCseId }}
            # Use auto-created ConfigMap when both values are provided
            - name: GOOGLE_API_KEY
              valueFrom:
                configMapKeyRef:
                  name: {{ include "google-search-mcp.fullname" . }}-config
                  key: GOOGLE_API_KEY
            - name: GOOGLE_CSE_ID
              valueFrom:
                configMapKeyRef:
                  name: {{ include "google-search-mcp.fullname" . }}-config
                  key: GOOGLE_CSE_ID
            {{- else }}
            # Use direct environment variables (from external source)
            - name: GOOGLE_API_KEY
              value: ""  # Expected to be set by external means
            - name: GOOGLE_CSE_ID
              value: ""  # Expected to be set by external means
            {{- end }}
            {{- else if .Values.secret.create }}
            # Use Kubernetes secrets
            - name: GOOGLE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "google-search-mcp.secretName" . }}
                  key: google-api-key
            - name: GOOGLE_CSE_ID
              valueFrom:
                secretKeyRef:
                  name: {{ include "google-search-mcp.secretName" . }}
                  key: google-cse-id
            {{- end }}
          {{- if ne .Values.mcp.transport "stdio" }}
          ports:
            - name: http
              containerPort: {{ .Values.mcp.server.port }}
              protocol: TCP
          {{- end }}
          {{- if and .Values.livenessProbe.enabled (ne .Values.mcp.transport "stdio") }}
          livenessProbe:
            {{- omit .Values.livenessProbe "enabled" | toYaml | nindent 12 }}
          {{- end }}
          {{- if and .Values.readinessProbe.enabled (ne .Values.mcp.transport "stdio") }}
          readinessProbe:
            {{- omit .Values.readinessProbe "enabled" | toYaml | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}