{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sharepoint-mcp.secretName" . }}
  labels:
    {{- include "sharepoint-mcp.labels" . | nindent 4 }}
type: Opaque
data:
  # SharePoint Configuration
  {{- if .Values.secret.sharepointSiteUrl }}
  sharepoint-site-url: {{ .Values.secret.sharepointSiteUrl | b64enc | quote }}
  {{- end }}
  # Azure AD Authentication
  {{- if .Values.secret.azureClientId }}
  azure-client-id: {{ .Values.secret.azureClientId | b64enc | quote }}
  {{- end }}
  {{- if .Values.secret.azureClientSecret }}
  azure-client-secret: {{ .Values.secret.azureClientSecret | b64enc | quote }}
  {{- end }}
  {{- if .Values.secret.azureTenantId }}
  azure-tenant-id: {{ .Values.secret.azureTenantId | b64enc | quote }}
  {{- end }}
{{- end }}