{{- if eq (include "accuweather-mcp.serviceEnabled" .) "true" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "accuweather-mcp.fullname" . }}
  labels:
    {{- include "accuweather-mcp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "accuweather-mcp.selectorLabels" . | nindent 4 }}
{{- end }}