{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "atlassian-mcp.secretName" . }}
  labels:
    {{- include "atlassian-mcp.labels" . | nindent 4 }}
type: Opaque
data:
  # Confluence credentials
  {{- if .Values.secret.confluenceUrl }}
  confluence-url: {{ .Values.secret.confluenceUrl | b64enc | quote }}
  {{- end }}
  {{- if .Values.secret.confluenceUsername }}
  confluence-username: {{ .Values.secret.confluenceUsername | b64enc | quote }}
  {{- end }}
  {{- if .Values.secret.confluenceApiToken }}
  confluence-api-token: {{ .Values.secret.confluenceApiToken | b64enc | quote }}
  {{- end }}
  {{- if .Values.secret.confluencePersonalToken }}
  confluence-personal-token: {{ .Values.secret.confluencePersonalToken | b64enc | quote }}
  {{- end }}
  # Jira credentials
  {{- if .Values.secret.jiraUrl }}
  jira-url: {{ .Values.secret.jiraUrl | b64enc | quote }}
  {{- end }}
  {{- if .Values.secret.jiraUsername }}
  jira-username: {{ .Values.secret.jiraUsername | b64enc | quote }}
  {{- end }}
  {{- if .Values.secret.jiraApiToken }}
  jira-api-token: {{ .Values.secret.jiraApiToken | b64enc | quote }}
  {{- end }}
  {{- if .Values.secret.jiraPersonalToken }}
  jira-personal-token: {{ .Values.secret.jiraPersonalToken | b64enc | quote }}
  {{- end }}
{{- end }}